function f_view_field(varargin)
% f_view_field('field','J','iElem',mesh3D.iElem.Layer0);
%--------------------------------------------------------------------------
% CHAMP3D PROJECT
% Author : Huu-Kien Bui, IREENA Lab - UR 4642, Nantes Universite'
% Huu-Kien.Bui@univ-nantes.fr
% Copyright (c) 2022 H-K. Bui, All Rights Reserved.
%--------------------------------------------------------------------------

for i = 1:nargin/2
    eval([varargin{2*i-1} '= varargin{2*i};']);
end

if strcmpi(field,'Jimage')
    quiver3(mesh3D.xCenT(iElem),...
            mesh3D.yCenT(iElem),...
            mesh3D.zCenT(iElem),...
            imag(System.Jx(iElem)),...
            imag(System.Jy(iElem)),...
            imag(System.Jy(iElem)),'k');
    axis equal;
end

if strcmpi(field,'Jreal')
    quiver3(mesh3D.xCenT(iElem),...
            mesh3D.yCenT(iElem),...
            mesh3D.zCenT(iElem),...
            real(System.Jx(iElem)),...
            real(System.Jy(iElem)),...
            real(System.Jy(iElem)),'k');
    axis equal;
end

if strcmpi(field,'Bimage')
    quiver3(mesh3D.xCenT(iElem),...
            mesh3D.yCenT(iElem),...
            mesh3D.zCenT(iElem),...
            imag(System.Bx(iElem)),...
            imag(System.By(iElem)),...
            imag(System.By(iElem)),'k');
    axis equal;
end

if strcmpi(field,'Breal')
    quiver3(mesh3D.xCenT(iElem),...
            mesh3D.yCenT(iElem),...
            mesh3D.zCenT(iElem),...
            real(System.Bx(iElem)),...
            real(System.By(iElem)),...
            real(System.By(iElem)),'k');
    axis equal;
end