function data = f_testdata(varargin)
%--------------------------------------------------------------------------
% CHAMP3D PROJECT
% Author : Huu-Kien Bui, IREENA Lab - UR 4642, Nantes Universite'
% Huu-Kien.Bui@univ-nantes.fr
% Copyright (c) 2022 H-K. Bui, All Rights Reserved.
%--------------------------------------------------------------------------

% data = f_testdata('elem_type','tri')
% data = f_testdata('elem_type','quad')
% data = f_testdata('elem_type','tet')
% data = f_testdata('elem_type','prism')
% data = f_testdata('elem_type','hex')

if mod(nargin,2) ~= 0 
    error([mfilename ': Check function arguments : #elem_type !']);
    return
end

for i = 1:nargin/2
    eval([varargin{2*i-1} '= varargin{2*i};']);
end

switch elem_type
    case {33,'tri'}
        node = [-0.5   -0.5    1.5    1.5    0.5    0.5;...
                 0.5   -0.5   -0.5    0.5   -0.5    0.5];
        elem = [2     6     4     3;...
                5     1     6     6;...
                1     5     3     5;...
                1     1     2     2];
    case {44,'quad'}
        node = [-0.5   0.5    1.5    1.5    0.5    -0.5;...
                 0.5   0.5    0.5   -0.5   -0.5    -0.5];
        elem = [6     3;...
                5     2;...
                2     5;...
                1     4;...
                1     2];
    case {46,'tet'}
        node = [0   1    0   0   1;...
                0   1    1   1   0;...
                0   0    0   1   0];
        elem = [1     4;...
                3     2;...
                4     3;...
                5     5;...
                1     2];
    case {69,'prism'}
        node = [0   1    0   0   1   1   0   1;...
                0   1    1   1   0   1   0   0;...
                0   0    0   1   0   1   1   1];
        elem = [1     2;...
                5     5;...
                3     3;...
                7     6;...
                8     8;...
                4     4;...
                1     2];
    case {812,'hex'}
        node = [0   2    2   1   0   1   1   0   1   0   2   2;...
                0   0    1   1   1   0   1   1   0   0   0   1;...
                0   0    1   0   0   0   1   1   1   1   1   0];
        elem = [1     6;...
                10    2;...
                8     12;...
                5     4;...
                6     9;...
                9     11;...
                7     3;...
                4     7;...
                1     2];
end

data.node = node;
data.elem = elem;

end